# Site Info
title: Liberty & Freedom
tagline: 'Liberty & Freedom'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://terencecooper.github.io" target="_blank">@terence</a>.'
baseurl: ""
url: http://terencecooper.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

future: true

version: 1.0.0

# About/contact
author:
  name: Terence A. Cooper
  description: Machine Learning Engineer, Data Scientist, Life long learner
  gravatar: 119e0d0d3e896dc62dcb3cdc287d5c67 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/terence-cooper-5a976b122
    github:    https://github.com/TerenceCooper
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://terencecooper.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/eiffel-tower-construction.jpg
  caption: Eiffel Tower Construction &copy; <a href="">The Internet</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: # 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_shortname: terence-blog
# disqus_shortname: disqus_7J7EZ2oH1S
disqus_url: "http://terence-blog.disqus.com"



